name: MediaWarp Docker Builder

on:
  workflow_dispatch:
    inputs:
      APP_VERSION:
        description: "Docker镜像版本号 (例如 v0.1.5 或 snapshot)"
        required: true
        default: "snapshot"
      IS_LATEST:
        description: "是否标记为 latest 标签"
        required: true
        default: false

env:
  APP_VERSION: ${{ github.event.inputs.APP_VERSION }}
  IS_LATEST: ${{ github.event.inputs.IS_LATEST }}

jobs:
  docker-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Show Inputs
        run: |
          echo "Docker镜像版本：${{ env.APP_VERSION }}"
          echo "是否标记为 latest：${{ env.IS_LATEST }}"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/mediawarp
          tags: |
            type=raw,value=latest,enable=${{ env.IS_LATEST }}
            type=raw,value=${{ env.APP_VERSION }},enable=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
            linux/s390x
          push: true
          build-args: |
            MEDIAWARP_VERSION=${{ env.APP_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha, scope=docker-cache
          cache-to: type=gha, scope=docker-cache, mode=max
